spring:
  jpa:
    generate-ddl: false
    show-sql: true
    properties.hibernate.format_sql: true
    hibernate.ddl-auto: none
  flyway:
    enabled: true
    baselineOnMigrate: true
    validateOnMigrate: true
    locations: classpath:db/migration
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
    org.flywaydb: INFO